// Code generated by mockery v2.14.1. DO NOT EDIT.

package processmock

import (
	context "context"

	model "github.com/slok/tfe-drift/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// WorkspaceCheckPlanGetter is an autogenerated mock type for the WorkspaceCheckPlanGetter type
type WorkspaceCheckPlanGetter struct {
	mock.Mock
}

// GetCheckPlan provides a mock function with given fields: ctx, id
func (_m *WorkspaceCheckPlanGetter) GetCheckPlan(ctx context.Context, id string) (*model.Plan, error) {
	ret := _m.Called(ctx, id)

	var r0 *model.Plan
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Plan); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Plan)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewWorkspaceCheckPlanGetter interface {
	mock.TestingT
	Cleanup(func())
}

// NewWorkspaceCheckPlanGetter creates a new instance of WorkspaceCheckPlanGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewWorkspaceCheckPlanGetter(t mockConstructorTestingTNewWorkspaceCheckPlanGetter) *WorkspaceCheckPlanGetter {
	mock := &WorkspaceCheckPlanGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
