// Code generated by mockery v2.14.1. DO NOT EDIT.

package processmock

import (
	context "context"

	model "github.com/slok/tfe-drift/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// WorkspaceCheckPlanCreator is an autogenerated mock type for the WorkspaceCheckPlanCreator type
type WorkspaceCheckPlanCreator struct {
	mock.Mock
}

// CreateCheckPlan provides a mock function with given fields: ctx, w, message
func (_m *WorkspaceCheckPlanCreator) CreateCheckPlan(ctx context.Context, w model.Workspace, message string) (*model.Plan, error) {
	ret := _m.Called(ctx, w, message)

	var r0 *model.Plan
	if rf, ok := ret.Get(0).(func(context.Context, model.Workspace, string) *model.Plan); ok {
		r0 = rf(ctx, w, message)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Plan)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.Workspace, string) error); ok {
		r1 = rf(ctx, w, message)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewWorkspaceCheckPlanCreator interface {
	mock.TestingT
	Cleanup(func())
}

// NewWorkspaceCheckPlanCreator creates a new instance of WorkspaceCheckPlanCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewWorkspaceCheckPlanCreator(t mockConstructorTestingTNewWorkspaceCheckPlanCreator) *WorkspaceCheckPlanCreator {
	mock := &WorkspaceCheckPlanCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
