// Code generated by mockery v2.14.1. DO NOT EDIT.

package processmock

import (
	context "context"

	model "github.com/slok/tfe-drift/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// WorkspaceLatestCheckPlanGetter is an autogenerated mock type for the WorkspaceLatestCheckPlanGetter type
type WorkspaceLatestCheckPlanGetter struct {
	mock.Mock
}

// GetLatestCheckPlan provides a mock function with given fields: ctx, w
func (_m *WorkspaceLatestCheckPlanGetter) GetLatestCheckPlan(ctx context.Context, w model.Workspace) (*model.Plan, error) {
	ret := _m.Called(ctx, w)

	var r0 *model.Plan
	if rf, ok := ret.Get(0).(func(context.Context, model.Workspace) *model.Plan); ok {
		r0 = rf(ctx, w)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Plan)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.Workspace) error); ok {
		r1 = rf(ctx, w)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewWorkspaceLatestCheckPlanGetter interface {
	mock.TestingT
	Cleanup(func())
}

// NewWorkspaceLatestCheckPlanGetter creates a new instance of WorkspaceLatestCheckPlanGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewWorkspaceLatestCheckPlanGetter(t mockConstructorTestingTNewWorkspaceLatestCheckPlanGetter) *WorkspaceLatestCheckPlanGetter {
	mock := &WorkspaceLatestCheckPlanGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
