coverage:
  range: 70..90 # First number represents red, and second represents green.
  status:
    patch: false
    project:
      default:
        # Allow going down 1% before being a failure.
        threshold: 1%
