// Code generated by mockery v2.14.1. DO NOT EDIT.

package prometheusmock

import (
	context "context"

	model "github.com/slok/tfe-drift/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetLatestCheckPlan provides a mock function with given fields: ctx, w
func (_m *Repository) GetLatestCheckPlan(ctx context.Context, w model.Workspace) (*model.Plan, error) {
	ret := _m.Called(ctx, w)

	var r0 *model.Plan
	if rf, ok := ret.Get(0).(func(context.Context, model.Workspace) *model.Plan); ok {
		r0 = rf(ctx, w)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Plan)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.Workspace) error); ok {
		r1 = rf(ctx, w)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListWorkspaces provides a mock function with given fields: ctx, includeTags, excludeTags
func (_m *Repository) ListWorkspaces(ctx context.Context, includeTags []string, excludeTags []string) ([]model.Workspace, error) {
	ret := _m.Called(ctx, includeTags, excludeTags)

	var r0 []model.Workspace
	if rf, ok := ret.Get(0).(func(context.Context, []string, []string) []model.Workspace); ok {
		r0 = rf(ctx, includeTags, excludeTags)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Workspace)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []string, []string) error); ok {
		r1 = rf(ctx, includeTags, excludeTags)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
